### ISSUE TITLE
Have altitude adjust temperature

### ISSUE THREAD

**Issue by Malvisk** [Globox1997/EnvironmentZ#44]
It is well known that underground caves actually stay rather nice in the winter.  So I'd recommend that as you descend beneath standard ground level the temperature slowly gets warmer.  In the winter being below Y = 0 should protect against the worst temps.  And as you gain altitude the temperature plummets.  At max build height, for snowy biomes it should be the absolute worst, even with cold weather gear there is a slight chilling effect to the point that after 3 days you start taking damage from the cold. =)

It would make mountain climbing really interesting. =)

**Comment by LordMeta** [comment]
This is a great idea! ^^ I think being underground, like in real life, should help with all temperature hot or Cold (depending on how deep you go as well) and climbing a very tall mountain should indeed get colder the higher you go up. This would be an insane advancement.

**Comment by LaiJoengzit** [comment]
like this idea and maybe when altitude gets too high or too far inside the caves, one may get Weakness due to hypoxia

**Comment by Globox1997** [comment]
Added height affection with [https://github.com/Globox1997/EnvironmentZ/commit/f2afb27761ab8ffb5271aa0b958e06159aa81133](https://github.com/Globox1997/EnvironmentZ/commit/f2afb27761ab8ffb5271aa0b958e06159aa81133)
It isn't a bad idea to calculate a new temperature since environmentz just uses the biome temperature, might be a good idea for a future update :D
