### ISSUE TITLE
Environment effects before damage?

### ISSUE THREAD

**Issue by Malvisk** [Globox1997/EnvironmentZ#45]
Would it be possible that as you progress through the levels, before you start taking effects you see a more visible effect.

For example, your character begins to shake as it gets cold.  The shaking doesn't need to increase in frequency.

This would be a cool effect, plus it would help players with a more visible indicator when they've wandered into dangerous territory.

**Comment by Globox1997** [comment]
Added a shaking effect with [https://github.com/Globox1997/EnvironmentZ/commit/1c394458cb4ad72592f453aa9963ba2c939b40dd](https://github.com/Globox1997/EnvironmentZ/commit/1c394458cb4ad72592f453aa9963ba2c939b40dd)
Might add an environment indication somehow too since this will only apply when the player temperature is pretty low
