### ISSUE TITLE
hypothermia bug

### ISSUE THREAD

**Issue by crimsonknight51** [Globox1997/EnvironmentZ#85]
campfires dont actually heat you up or stop hypothermia from dealing damage to you

**Comment by Globox1997** [comment]
Which mod version are you using?

**Comment by RCertainty** [comment]
> Which mod version are you using?

Been having the same issue on the current version (fabric 2.0.0) with the Medieval MC Modpack, which just updated your mod to the latest version. Campfires no longer heat you up at all I tried placing one down to prevent my death but it did not work.

Also, another issue is that since this update, I can't go to cold biomes or I will freeze to death within a minute without heating stone, full armor, and warming potion, and the same goes for hot biomes but opposite, I need to not wear armor, have an icepack, and cooling potion to not die very quickly but this also may possibly an issue with configs being outdated as the changelog said you revamped the entire temp system, so maybe add some documentation on what you changed so I can fix it accordingly.

As well when I remove the insulation of armor with shears, it keeps the gap of where the insulation text used to be. This is minor but distracting when it is on an item that has a description as it has just a random gap.

Another thing is that while I was inside it was still extremely cold or extremely hot, there seems to be no more temp protection from being inside, I died inside next to a campfire, full armor, warming potion, etc.

**Comment by easyaspi314** [comment]
This *may* be fixed in c005931dad1218a7ceea7fad0822018ea9834c97 but it hasn't been released. 

The current state is absolutely broken because block temperatures seem to be adjusting by a constant amount instead of based on the player temperature, and it makes it basically unplayable.

**Comment by muon-rw** [comment]
> Also, another issue is that since this update, I can't go to cold biomes or I will freeze to death within a minute without heating stone, full armor, and warming potion, and the same goes for hot biomes but opposite, I need to not wear armor, have an icepack, and cooling potion to not die very quickly but this also may possibly an issue with configs being outdated as the changelog said you revamped the entire temp system, so maybe add some documentation on what you changed so I can fix it accordingly.


Your hunch was correct, some of the customizations made to Medieval MC’s environmentZ settings now have to be done via datapack. The great advantage is that it’s now much more configurable but it’s taken some time to get ready and it wasn’t anticipated this would need to be done. 

It’s been finished and *most* (maybe not all) of the issues in your comment should be addressed by the next update (v20.5, not released just yet) and are not an issue with EnvironmentZ itself.

As far as update notes, to my knowledge almost all of the changes are encompassed by the temperature datapack system, documented on the readme here on GitHub, though I agree it could use some more description in some places. 

Specifically a brief overview of how *exactly* player temperature is calculated given the numbers would be extremely welcome.

**Comment by Globox1997** [comment]
Definitely open for better description at the readme ;)
I guess this can be closed. Reopen if a bug is persistent on the latest version.
